AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  picked-lambdas

  SAM Template for picked-lambdas

Resources:
  ContentProcessorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/content_processor.asl.json
      DefinitionSubstitutions:
        WebhookFunctionArn: !GetAtt WebhookFunction.Arn
        ArticleScraperFunctionArn: !GetAtt ArticleScraperFunction.Arn
        ImageHandlerFunctionArn: !GetAtt ImageHandlerFunction.Arn
        NotifierFunctionArn: !GetAtt NotifierFunction.Arn
      Events:
        ApiGatewayTrigger:
          Type: Api
          Properties:
            Method: post
            Path: /{sourceId}
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref WebhookFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ArticleScraperFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ImageHandlerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifierFunction

  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/webhook/
      Handler: app.webhook
      Runtime: nodejs14.x
      Environment:
        Variables:
          WEBHOOK_SECRET: !Ref WebhookSecret

  ArticleScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/article-scraper/
      Handler: app.scraper
      Layers:
        - !Ref ScraperDepsLayer
      Runtime: nodejs14.x
      Timeout: 50
      MemorySize: 1024

  ImageHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/image-handler/
      Handler: app.imageHandler
      Runtime: nodejs14.x
      Timeout: 60
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "${ImageBucketName}"
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucketName
          BUCKET_REGION: !Ref ImageBucketRegion

  NotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/notifier/
      Handler: app.notifier
      Runtime: nodejs14.x
      Timeout: 60
      Environment:
        Variables:
          CALLBACK_URL: !Ref CallbackUrl
          CALLBACK_SECRET: !Ref CallbackSecret

  ScraperDepsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs14.x
      ContentUri: layers/scraper-deps/
      Description: Dependencies for web scraping
      LayerName: ScraperDepsLayer
    Metadata:
      BuildMethod: nodejs14.x

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ImageBucketName

Parameters:
  WebhookSecret:
    Type: String
  ImageBucketName:
    Type: String
    Default: "picked-dev"
  ImageBucketRegion:
    Type: String
    Default: "ap-south-1"
  CallbackUrl:
    Type: String
  CallbackSecret:
    Type: String

Outputs:
  ContentProcessorStateMachineArn:
    Description: "Content Processing state machine ARN"
    Value: !Ref ContentProcessorStateMachine
  ContentProcessorStateMachineRole:
    Description: "IAM Role created for Content Processing state machine based on the specified SAM Policy Templates"
    Value: !GetAtt ContentProcessorStateMachineRole.Arn
