AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  picked-lambdas

  SAM Template for picked-lambdas

Resources:
  ContentProcessorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/content_processor.asl.json
      DefinitionSubstitutions:
        WebhookFunctionArn: !GetAtt WebhookFunction.Arn
      Events:
        ApiGatewayTrigger:
          Type: Api
          Properties:
            Path: /
            Method: post
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref WebhookFunction

  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/webhook/
      Handler: app.webhook
      Runtime: nodejs14.x
      Environment:
        Variables:
          WebhookSecret: !Ref WebhookSecret
    
Parameters:
  WebhookSecret:
    Type: String

Outputs:
  ContentProcessorStateMachineArn:
    Description: "Content Processing state machine ARN"
    Value: !Ref ContentProcessorStateMachine
  ContentProcessorStateMachineRole:
    Description: "IAM Role created for Content Processing state machine based on the specified SAM Policy Templates"
    Value: !GetAtt ContentProcessorStateMachineRole.Arn
